- name: Add Kubernetes apt key
  apt_key:
    url: https://pkgs.k8s.io/core:/stable:/v1.30/deb/Release.key
    state: present

- name: Add Kubernetes repo
  apt_repository:
    repo: deb https://pkgs.k8s.io/core:/stable:/v1.30/deb/ /
    state: present

- name: Install kubeadm, kubelet, kubectl
  apt:
    name:
      - kubelet
      - kubeadm
      - kubectl
    state: present
    update_cache: yes

- name: Hold Kubernetes packages
  command: apt-mark hold kubelet kubeadm kubectl
  become: yes

- name: Initialize Kubernetes master
  command: kubeadm init --pod-network-cidr=10.244.0.0/16
  args:
    creates: /etc/kubernetes/admin.conf
