- name: Update apt cache
  apt:
    update_cache: yes
    force_apt_get: yes

- name: Install required packages
  apt:
    name: ['apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common']
    state: present

- name: Add Docker GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker repo
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu jammy stable
    state: present

- name: Install Docker
  apt:
    name: ['docker-ce', 'docker-ce-cli', 'containerd.io']
    state: present

- name: Ensure Docker service is started
  systemd:
    name: docker
    state: started
    enabled: yes

- name: Disable swap
  command: swapoff -a
  become: true

- name: Comment swap in /etc/fstab
  replace:
    path: /etc/fstab
    regexp: '^(.*swap.*)$'
    replace: '# \1'
